version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cldrojas
      POSTGRES_PASSWORD: 123pollo
      POSTGRES_DB: eira
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=cld.rojas@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123pollo
    ports:
      - 5050:80
